apiVersion: apps/v1
kind: Deployment
metadata:
  name: connect
  namespace: eda
spec:
  replicas: 1
  selector:
    matchLabels:
      app: connect
  template:
    metadata:
      labels:
        app: connect
    spec:
      containers:
        - name: connect
          image: quay.io/debezium/connect:2.7.3.Final
          ports:
            - containerPort: 8083
          env:
            - { name: BOOTSTRAP_SERVERS, value: "kafka:9092" }
            - { name: GROUP_ID, value: "connect-cluster" }
            - { name: CONFIG_STORAGE_TOPIC, value: "connect_configs" }
            - { name: OFFSET_STORAGE_TOPIC, value: "connect_offsets" }
            - { name: STATUS_STORAGE_TOPIC, value: "connect_statuses" }
            - { name: CONNECT_CONFIG_STORAGE_REPLICATION_FACTOR, value: "1" }
            - { name: CONNECT_OFFSET_STORAGE_REPLICATION_FACTOR, value: "1" }
            - { name: CONNECT_STATUS_STORAGE_REPLICATION_FACTOR, value: "1" }
            - { name: KEY_CONVERTER, value: "org.apache.kafka.connect.json.JsonConverter" }
            - { name: VALUE_CONVERTER, value: "org.apache.kafka.connect.json.JsonConverter" }
            - { name: KEY_CONVERTER_SCHEMAS_ENABLE, value: "false" }
            - { name: VALUE_CONVERTER_SCHEMAS_ENABLE, value: "false" }
            - { name: REST_ADVERTISED_HOST_NAME, value: "connect" }
          readinessProbe:
            httpGet: { path: "/", port: 8083 }
            initialDelaySeconds: 10
            periodSeconds: 5
          livenessProbe:
            httpGet: { path: "/", port: 8083 }
            initialDelaySeconds: 20
            periodSeconds: 10
