apiVersion: v1
kind: Service
metadata:
  name: flink-jobmanager
  namespace: eda
spec:
  selector:
    app: flink-jobmanager
  ports:
    - name: web
      port: 8081
      targetPort: 8081
  type: ClusterIP
