apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kafka-data
  namespace: eda
spec:
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: 20Gi
  # storageClassName: standard
